---
abstract: 'export constants'
author:
  - 'Robert Rothenberg, C<< <rrwo at cpan.org> >>'
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Most: 0
  Test::Warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Const-Exporter
no_index:
  directory:
    - inc
    - t
recommends:
  Package::Stash::XS: 0
  Storable: 0
requires:
  Carp: 0
  Const::Fast: 0.014
  Exporter: 0
  List::MoreUtils: 0.09
  Package::Stash: 0
  Scalar::Util: 0
  perl: 5.01
  version: 0.77
resources:
  bugtracker: https://github.com/robrwo/Const-Exporter/issues
  homepage: http://rrwo.tumblr.com
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/robrwo/Const-Exporter.git
version: 0.001000
